version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
