version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
    versioning-strategy: increase
    groups:
      dependencies:
        dependency-type: "production"
      devDependencies:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
